org: wongsuihuang
app: aws-node-simple-http-endpoint
service: aws-node-simple-http-endpoint
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  localGreeting:
    handler: handler.endpoint
